export const actionTypes = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_PLAYING: "SET_PLAYING",
  SET_TRACK_STATE: "SET_TRACK_STATE",
};
